// Licensed under the Apache-2.0 license

//! Certificate Store Platform Implementation
//!
//! Provides certificate management using static certificates with ECDSA signing

use std::sync::Mutex;

#[cfg(feature = "crypto")]
use p384::{
    ecdsa::{signature::Signer, Signature, SigningKey},
    SecretKey,
};

use super::certs::{STATIC_ATTESTATION_CERT, STATIC_CERTIFICATE_CHAIN, STATIC_ROOT_CA_CERT};
use spdm_lib::protocol::algorithms::{AsymAlgo, ECC_P384_SIGNATURE_SIZE, SHA384_HASH_SIZE};
use spdm_lib::protocol::certs::{CertificateInfo, KeyUsageMask};
use spdm_lib::{
    cert_store::{CertStoreError, CertStoreResult, PeerCertStore, ReassemblyStatus, SpdmCertStore},
    error::PlatformError,
};

/// Certificate store with proper ECDSA signing
pub struct DemoCertStore {
    cert_chain: Vec<u8>,
    #[cfg(feature = "crypto")]
    signing_key: Mutex<Option<SigningKey>>,
}

impl DemoCertStore {
    pub fn new() -> Self {
        #[cfg(feature = "crypto")]
        {
            println!("Loading static certificate chain...");
            let (cert_chain, signing_key) = Self::generate_certificate_chain();
            println!("Static certificate chain loaded successfully");

            Self {
                cert_chain,
                signing_key: Mutex::new(Some(signing_key)),
            }
        }

        #[cfg(not(feature = "crypto"))]
        {
            // Fallback for when crypto feature is not enabled
            let cert_chain = b"DEMO_CERTIFICATE_CHAIN_DATA".to_vec();
            Self { cert_chain }
        }
    }

    #[cfg(feature = "crypto")]
    fn generate_certificate_chain() -> (Vec<u8>, SigningKey) {
        use rand::rngs::OsRng;

        // Use static certificates generated by OpenSSL
        println!("Using static OpenSSL-generated certificates");

        // Convert the static certificate chain to Vec<u8>
        let cert_chain = STATIC_CERTIFICATE_CHAIN.to_vec();

        // Generate a key for signing (we can't extract the key from certificates)
        let attestation_key = SecretKey::random(&mut OsRng);
        let attestation_signing_key = SigningKey::from(&attestation_key);

        println!("Certificate chain loaded: {} bytes", cert_chain.len());
        println!("Root CA certificate: {} bytes", STATIC_ROOT_CA_CERT.len());
        println!(
            "Attestation certificate: {} bytes",
            STATIC_ATTESTATION_CERT.len()
        );

        (cert_chain, attestation_signing_key)
    }

    /// Extract the first certificate from a DER-encoded certificate chain
    #[allow(dead_code)]
    fn extract_first_certificate_der<'a>(&self, cert_chain: &'a [u8]) -> Option<&'a [u8]> {
        if cert_chain.len() < 2 {
            return None;
        }

        let mut offset = 0;

        // Check for SEQUENCE tag (0x30)
        if cert_chain[offset] != 0x30 {
            return None;
        }
        offset += 1;

        // Parse length and calculate total certificate size
        let (content_length, header_size) = if cert_chain[offset] & 0x80 == 0 {
            // Short form length (0-127)
            let content_len = cert_chain[offset] as usize;
            let header_len = 2; // tag + 1 byte length
            (content_len, header_len)
        } else {
            // Long form length
            let length_octets = (cert_chain[offset] & 0x7f) as usize;
            if length_octets == 0 || length_octets > 4 {
                return None;
            }
            offset += 1;

            if offset + length_octets > cert_chain.len() {
                return None;
            }

            let mut content_len = 0;
            for i in 0..length_octets {
                content_len = (content_len << 8) | cert_chain[offset + i] as usize;
            }

            let header_len = 2 + length_octets; // tag + length indicator + length bytes
            (content_len, header_len)
        };

        let total_cert_size = header_size + content_length;

        if total_cert_size > cert_chain.len() {
            return None;
        }

        Some(&cert_chain[0..total_cert_size])
    }
}

impl SpdmCertStore for DemoCertStore {
    fn slot_count(&self) -> u8 {
        1 // Only support slot 0
    }

    fn is_provisioned(&self, slot_id: u8) -> bool {
        slot_id == 0 // Only slot 0 is provisioned
    }

    fn cert_chain_len(&mut self, _asym_algo: AsymAlgo, slot_id: u8) -> CertStoreResult<usize> {
        if slot_id == 0 {
            Ok(self.cert_chain.len())
        } else {
            Err(CertStoreError::InvalidSlotId(slot_id))
        }
    }

    fn get_cert_chain<'a>(
        &mut self,
        slot_id: u8,
        _asym_algo: AsymAlgo,
        offset: usize,
        cert_portion: &'a mut [u8],
    ) -> CertStoreResult<usize> {
        if slot_id != 0 {
            return Err(CertStoreError::InvalidSlotId(slot_id));
        }

        if offset >= self.cert_chain.len() {
            return Ok(0);
        }

        let remaining = self.cert_chain.len() - offset;
        let copy_len = remaining.min(cert_portion.len());

        cert_portion[..copy_len].copy_from_slice(&self.cert_chain[offset..offset + copy_len]);
        Ok(copy_len)
    }

    fn root_cert_hash<'a>(
        &mut self,
        slot_id: u8,
        _asym_algo: AsymAlgo,
        cert_hash: &'a mut [u8; SHA384_HASH_SIZE],
    ) -> CertStoreResult<()> {
        if slot_id != 0 {
            return Err(CertStoreError::InvalidSlotId(slot_id));
        }

        // For demo: simple hash of the first bytes
        for (i, byte) in cert_hash.iter_mut().enumerate() {
            *byte = self
                .cert_chain
                .get(i % self.cert_chain.len())
                .copied()
                .unwrap_or(0);
        }

        Ok(())
    }

    fn sign_hash<'a>(
        &self,
        slot_id: u8,
        hash: &'a [u8; SHA384_HASH_SIZE],
        signature: &'a mut [u8; ECC_P384_SIGNATURE_SIZE],
    ) -> CertStoreResult<()> {
        if slot_id != 0 {
            return Err(CertStoreError::InvalidSlotId(slot_id));
        }

        #[cfg(feature = "crypto")]
        {
            if let Ok(signing_key_guard) = self.signing_key.lock() {
                if let Some(ref signing_key) = *signing_key_guard {
                    let sig: Signature = signing_key.sign(hash);
                    let sig_bytes = sig.to_bytes();
                    if sig_bytes.len() <= ECC_P384_SIGNATURE_SIZE {
                        signature[..sig_bytes.len()].copy_from_slice(&sig_bytes);
                        return Ok(());
                    }
                }
            }
            Err(CertStoreError::PlatformError)
        }

        #[cfg(not(feature = "crypto"))]
        {
            // Fallback for demo without crypto
            for (i, byte) in signature.iter_mut().enumerate() {
                *byte = hash[i % SHA384_HASH_SIZE] ^ ((i as u8).wrapping_mul(73));
            }
            Ok(())
        }
    }

    fn key_pair_id(&self, slot_id: u8) -> Option<u8> {
        if slot_id == 0 {
            Some(1)
        } else {
            None
        }
    }

    fn cert_info(&self, slot_id: u8) -> Option<CertificateInfo> {
        if slot_id != 0 {
            return None;
        }

        let mut cert_info = CertificateInfo(0);
        cert_info.set_cert_model(1);
        Some(cert_info)
    }

    fn key_usage_mask(&self, slot_id: u8) -> Option<KeyUsageMask> {
        if slot_id != 0 {
            return None;
        }

        let mut key_usage = KeyUsageMask::default();
        key_usage.set_challenge_usage(1);
        key_usage.set_measurement_usage(1);
        Some(key_usage)
    }
}

#[derive(Debug)]
pub struct PeerSlot {
    /// CertChain[K], retrieved in `CERTIFICATE` response.
    pub cert_chain: Vec<u8>,

    /// Digest[K], retrieved in `DIGESTS` response.
    pub digest: Vec<u8>,

    /// `KeyPairID[K]`, retrieved in `DIGESTS` response if the corresponding `MULTI_KEY_CONN_REQ` or `MULTI_KEY_CONN_RSP` is true.
    pub keypair_id: Option<u8>,

    /// `CertificateInfo[K]`, retrieved in `DIGESTS` response if the corresponding `MULTI_KEY_CONN_REQ` or `MULTI_KEY_CONN_RSP` is true. pub cert_info: Option<CertificateInfo>
    pub certificate_info: Option<CertificateInfo>,

    /// KeyUsageMask[K], retrieved in `DIGESTS` response if the corresponding `MULTI_KEY_CONN_REQ` or `MULTI_KEY_CONN_RSP` is true.
    pub key_usage_mask: Option<KeyUsageMask>,
}

impl Default for PeerSlot {
    fn default() -> Self {
        PeerSlot {
            cert_chain: Vec::new(),
            digest: Vec::new(),
            keypair_id: None,
            certificate_info: None,
            key_usage_mask: None,
        }
    }
}

/// Concrete implementation of `PeerCertStore` for demonstration purposes.
/// This example store manages a single certificate slot (slot 0) and allows
/// setting and retrieving the certificate chain, digest, key pair ID, certificate info,
/// and key usage mask for that slot. In a real implementation, you would likely
/// want to support multiple slots and have more robust error handling and storage mechanisms.
#[derive(Debug)]
pub struct ExamplePeerCertStore {
    /// Retrieved from `DIGESTS` response, indicates which certificate slots are supported by the peer.
    supported_slots_mask: u8,

    /// Retrieved from `DIGESTS` response, indicates which certificate slots are provisioned with valid certificate chains.
    provisioned_slots_mask: u8,

    // Since not all existing slots may hold eligible certificate chains, keep the PeerSlot values optional.
    pub peer_slots: Vec<Option<PeerSlot>>,
}

impl Default for ExamplePeerCertStore {
    fn default() -> Self {
        ExamplePeerCertStore {
            supported_slots_mask: 0,
            provisioned_slots_mask: 0,
            peer_slots: vec![None],
        }
    }
}

impl PeerCertStore for ExamplePeerCertStore {
    fn slot_count(&self) -> u8 {
        self.peer_slots.len() as u8
    }

    fn assemble(
        &mut self,
        slot_id: u8,
        portion: &[u8],
    ) -> Result<spdm_lib::cert_store::ReassemblyStatus, CertStoreError> {
        let slot = self
            .peer_slots
            .get_mut(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_mut()
            .ok_or(CertStoreError::PlatformError)?;

        slot.cert_chain.extend_from_slice(portion);

        Ok(spdm_lib::cert_store::ReassemblyStatus::InProgress)
    }

    fn reset(&mut self, _slot_id: u8) {
        todo!()
    }

    fn get_root_hash(&self, _slot_id: u8) -> Option<&[u8]> {
        todo!()
    }

    fn get_raw_chain(&self, _slot_id: u8) -> Option<&[u8]> {
        todo!()
    }

    fn get_cert_chain(&self, slot_id: u8) -> CertStoreResult<&[u8]> {
        let slot = self
            .peer_slots
            .get(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_ref()
            .ok_or(CertStoreError::PlatformError)?;
        Ok(&slot.cert_chain)
    }

    /// Set the supported slots bit mask and initialize PeerSlot entries for any newly supported slots.  
    fn set_supported_slots(&mut self, slot_mask: u8) -> CertStoreResult<()> {
        for b in 0..8 {
            if slot_mask & (1 << b) == 1 {
                if let Some(slot) = self.peer_slots.get_mut(b as usize) {
                    if slot.is_none() {
                        *slot = Some(PeerSlot::default());
                    }
                }
            }
        }

        Ok(())
    }

    fn get_supported_slots(&self) -> CertStoreResult<u8> {
        Ok(self.supported_slots_mask)
    }

    fn set_provisioned_slots(&mut self, provisioned_slot_mask: u8) -> CertStoreResult<()> {
        self.provisioned_slots_mask = provisioned_slot_mask;
        Ok(())
    }

    fn get_provisioned_slots(&self) -> CertStoreResult<u8> {
        Ok(self.provisioned_slots_mask)
    }

    /// Set the certificate chain for a given slot. This would typically be called
    /// after successfully reassembling the certificate chain from received portions.
    ///
    /// # Returns
    /// - `Ok(())` if the certificate chain was set successfully
    /// - `Err(CertStoreError)` if there was an error (e.g., invalid slot ID)
    fn set_cert_chain(&mut self, slot_id: u8, cert_chain: &[u8]) -> CertStoreResult<()> {
        let slot = self
            .peer_slots
            .get_mut(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_mut()
            .ok_or(CertStoreError::PlatformError)?;

        slot.cert_chain = cert_chain.to_vec();
        Ok(())
    }

    fn get_digest(&self, slot_id: u8) -> CertStoreResult<&[u8]> {
        let slot = self
            .peer_slots
            .get(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_ref()
            .ok_or(CertStoreError::PlatformError)?;
        Ok(&slot.digest)
    }

    /// Set the digest for a given slot, provided by the `DIGESTS` response.
    ///
    /// # Parameters
    /// - `slot_id`: The slot ID to set the digest for
    /// - `digest`: The digest value to set
    fn set_digest(&mut self, slot_id: u8, digest: &[u8]) -> CertStoreResult<()> {
        let slot: &mut PeerSlot = self
            .peer_slots
            .get_mut(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_mut()
            .ok_or(CertStoreError::PlatformError)?;
        slot.digest = digest.to_vec();
        Ok(())
    }

    fn get_cert_info(&self, slot_id: u8) -> CertStoreResult<CertificateInfo> {
        let slot = self
            .peer_slots
            .get(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_ref()
            .ok_or(CertStoreError::PlatformError)?;
        slot.certificate_info
            .ok_or(CertStoreError::InvalidSlotId(slot_id))
    }
    fn set_cert_info(&mut self, slot_id: u8, cert_info: CertificateInfo) -> CertStoreResult<()> {
        let slot = self
            .peer_slots
            .get_mut(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_mut()
            .ok_or(CertStoreError::PlatformError)?;
        slot.certificate_info = Some(cert_info);
        Ok(())
    }
    fn get_key_usage_mask(&self, slot_id: u8) -> CertStoreResult<KeyUsageMask> {
        let slot = self
            .peer_slots
            .get(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_ref()
            .ok_or(CertStoreError::PlatformError)?;
        slot.key_usage_mask
            .ok_or(CertStoreError::InvalidSlotId(slot_id))
    }

    fn set_key_usage_mask(
        &mut self,
        slot_id: u8,
        key_usage_mask: KeyUsageMask,
    ) -> CertStoreResult<()> {
        let slot = self
            .peer_slots
            .get_mut(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_mut()
            .ok_or(CertStoreError::PlatformError)?;
        slot.key_usage_mask = Some(key_usage_mask);
        Ok(())
    }

    fn get_keypair(&self, slot_id: u8) -> CertStoreResult<u8> {
        let slot = self
            .peer_slots
            .get(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_ref()
            .ok_or(CertStoreError::PlatformError)?;
        slot.keypair_id
            .ok_or(CertStoreError::InvalidSlotId(slot_id))
    }

    fn set_keypair(&mut self, slot_id: u8, keypair: u8) -> CertStoreResult<()> {
        let slot = self
            .peer_slots
            .get_mut(slot_id as usize)
            .ok_or(CertStoreError::InvalidSlotId(slot_id))?
            .as_mut()
            .ok_or(CertStoreError::PlatformError)?;
        slot.keypair_id = Some(keypair);
        Ok(())
    }
}
